INSERT INTO `bodasystem` VALUES ('Date,Name,Card_number,Account,Amount',1,'excel','F,H,Z,AD,AH');
INSERT INTO `bodasystem` VALUES ('Address,Address2,City,State,Zipcode,Phone,Email,Memo,Branch',0,'excel', 'L,N,P,R,T,V,X,AB,-');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', ':');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Ltd');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'The\\s');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', '\\sthe\\s');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Co\\.');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Co$');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Co\\s');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'University');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Federation');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Foundation');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Library');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'School');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Company');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Association');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Center');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'Inc');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'LLC');
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', "'s\\s");
INSERT INTO `bodasystem` VALUES ('business','array','BusinessFlags', 'unknown donor');
INSERT INTO `bodasystem` VALUES ('family','card number','attribute', 'FAMILY');
INSERT INTO `bodasystem` VALUES ('mail','Yes_No','attribute', 'MAIL');
INSERT INTO `bodasystem` VALUES ('publish','Yes_No','attribute', 'PUBLISH');
INSERT INTO `bodasystem` VALUES ('select','SCODE','attribute', 'SELECT'); 
INSERT INTO `bodasystem` VALUES ('bus','catBUS','category', 'BUS');
INSERT INTO `bodasystem` VALUES ('ind','catIND','category', 'PT');
INSERT INTO `bodasystem` VALUES ('branch','branch','category', 'FPL');