<div id="breadcrumbs">
<a href="/cgi-bin/koha/mainpage.pl">Home</a> &rsaquo;
<a href="/cgi-bin/koha/plugins/plugins-home.pl"> Plugins</a> 
<a href="/cgi-bin/koha/plugins/run.pl?class=Koha::Plugin::DonorApp&method=tool&taction=trace&tsubaction=show&action=[% action %]&subaction=[% subaction %]" >&rsaquo;</a>
<a href="/cgi-bin/koha/plugins/run.pl?class=Koha::Plugin::DonorApp&method=tool&action=Home">Donor Application</a>
</div>
<h2><a href="/cgi-bin/koha/plugins/run.pl?class=Koha::Plugin::DonorApp&method=tool&action=Home">Donor Application</a></h2>
<!-- Still can't get the damn logo to show  
  <img alt="Donor Application" src='[% logo %]' border='0' width='235' height='74'>
-->  

